import { Component, computed, inject, signal } from '@angular/core';
import { CommonModule, CurrencyPipe } from '@angular/common';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { Product, StoreService } from '../core/store.service';

@Component({ standalone: true, imports: [RouterLink], template: `
<section class="hero py-5"><div class="container py-5"><div class="row align-items-center"><div class="col-lg-7"><p class="text-uppercase fw-bold">تجربة تسوق سهلة</p><h1 class="display-3 fw-bold">كل ما تحتاجه في مكان واحد</h1><p class="lead my-4">متجر Angular تدريبي متجاوب، مع منتجات وسلة مشتريات تعمل فعليًا.</p><a routerLink="/products" class="btn btn-light btn-lg px-4">تصفح المنتجات <i class="bi bi-arrow-left"></i></a></div><div class="col-lg-5 text-center d-none d-lg-block"><i class="bi bi-bag-check-fill" style="font-size:12rem"></i></div></div></div></section>
<section class="container py-5"><h2 class="text-center fw-bold mb-4">لماذا متجرنا؟</h2><div class="row g-4 text-center"><div class="col-md-4"><i class="bi bi-truck fs-1 text-primary"></i><h5>شحن سريع</h5><p class="text-muted">طلبك يصل بأمان وسرعة.</p></div><div class="col-md-4"><i class="bi bi-shield-check fs-1 text-success"></i><h5>دفع آمن</h5><p class="text-muted">واجهة مريحة وآمنة للمستخدم.</p></div><div class="col-md-4"><i class="bi bi-headset fs-1 text-warning"></i><h5>دعم دائم</h5><p class="text-muted">نحن هنا لخدمتك طوال الوقت.</p></div></div></section>` })
export class HomeComponent {}

@Component({ standalone: true, imports: [CommonModule, FormsModule, RouterLink, CurrencyPipe], template: `
<section class="container py-5"><div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h1 class="fw-bold mb-1">المنتجات</h1><p class="text-muted mb-0">اختاري ما يناسبك من منتجاتنا</p></div><input class="form-control w-auto" style="min-width:230px" placeholder="ابحثي عن منتج..." [(ngModel)]="query"></div>
<div class="mb-4"><button class="btn btn-sm me-2" [class.btn-primary]="category()==='الكل'" [class.btn-outline-primary]="category()!=='الكل'" (click)="category.set('الكل')">الكل</button>@for (item of categories; track item) { <button class="btn btn-sm me-2" [class.btn-primary]="category()===item" [class.btn-outline-primary]="category()!==item" (click)="category.set(item)">{{item}}</button> }</div>
<div class="row g-4">@for (product of filtered(); track product.id) {<div class="col-sm-6 col-lg-3"><div class="card h-100"><img class="product-image card-img-top" [src]="product.image" [alt]="product.title"><div class="card-body d-flex flex-column"><small class="text-primary">{{product.category}}</small><h5 class="mt-2">{{product.title}}</h5><div class="text-warning mb-2"><i class="bi bi-star-fill"></i> {{product.rating}}</div><strong class="fs-5">{{product.price | currency:'USD'}}</strong><div class="mt-auto pt-3 d-grid gap-2"><a class="btn btn-outline-primary" [routerLink]="['/products', product.id]">التفاصيل</a><button class="btn btn-primary" (click)="addToCart(product)"><i class="bi bi-cart-plus"></i> أضف للسلة</button><button class="btn btn-outline-danger" (click)="toggleFavorite(product)"><i class="bi" [class.bi-heart]="!store.isFavorite(product.id)" [class.bi-heart-fill]="store.isFavorite(product.id)"></i> المفضلة</button></div></div></div></div>} @empty {<p class="text-muted">لا توجد منتجات مطابقة.</p>}</div></section>` })
export class ProductsComponent {
  readonly store = inject(StoreService); private readonly router = inject(Router); query = ''; readonly category = signal('الكل'); readonly categories = ['إلكترونيات', 'ملابس رجالية', 'مجوهرات', 'ملابس نسائية'];
  readonly filtered = computed(() => this.store.products().filter(p => (this.category() === 'الكل' || p.category === this.category()) && p.title.includes(this.query)));
  addToCart(product: Product) { if (!this.store.addToCart(product)) void this.router.navigateByUrl('/login'); }
  toggleFavorite(product: Product) { if (!this.store.isAuthenticated()) { void this.router.navigateByUrl('/login'); return; } this.store.toggleFavorite(product); }
}

@Component({ standalone: true, imports: [CommonModule, RouterLink, CurrencyPipe], template: `
<section class="container py-5">@if (product()) {<div class="row g-5 align-items-center"><div class="col-md-5"><div class="card"><img class="img-fluid product-image" style="height:420px" [src]="product()!.image" [alt]="product()!.title"></div></div><div class="col-md-7"><a routerLink="/products" class="text-decoration-none">← العودة للمنتجات</a><p class="text-primary mt-3">{{product()!.category}}</p><h1 class="fw-bold">{{product()!.title}}</h1><div class="text-warning fs-5"><i class="bi bi-star-fill"></i> {{product()!.rating}} / 5</div><p class="lead text-muted my-4">{{product()!.description}}</p><h2>{{product()!.price | currency:'USD'}}</h2><div class="d-flex gap-2 mt-3"><button class="btn btn-primary btn-lg" (click)="addToCart(product()!)"><i class="bi bi-cart-plus"></i> أضف إلى السلة</button><button class="btn btn-outline-danger btn-lg" (click)="toggleFavorite(product()!)"><i class="bi" [class.bi-heart]="!store.isFavorite(product()!.id)" [class.bi-heart-fill]="store.isFavorite(product()!.id)"></i></button></div></div></div>} @else {<div class="text-center py-5"><h2>المنتج غير موجود</h2><a routerLink="/products">العودة للمنتجات</a></div>}</section>` })
export class ProductDetailsComponent { readonly store = inject(StoreService); private route = inject(ActivatedRoute); private router = inject(Router); readonly product = computed(() => this.store.product(this.route.snapshot.paramMap.get('id') || '')); addToCart(product: Product) { if (!this.store.addToCart(product)) void this.router.navigateByUrl('/login'); } toggleFavorite(product: Product) { if (!this.store.isAuthenticated()) { void this.router.navigateByUrl('/login'); return; } this.store.toggleFavorite(product); } }

@Component({ standalone: true, imports: [CommonModule, RouterLink, CurrencyPipe], template: `
<section class="container py-5"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="fw-bold mb-1">المفضلة</h1><p class="text-muted mb-0">المنتجات التي حفظتها للرجوع إليها لاحقًا</p></div><a class="btn btn-outline-primary" routerLink="/products">تصفح المنتجات</a></div>@if (!store.isAuthenticated()) {<div class="card p-5 text-center"><i class="bi bi-heart fs-1 text-muted"></i><h3 class="mt-3">سجّل الدخول لعرض المفضلة</h3><a class="btn btn-primary mx-auto" routerLink="/login">تسجيل الدخول</a></div>} @else if (store.favorites().length) {<div class="row g-4">@for (product of store.favorites(); track product.id) {<div class="col-sm-6 col-lg-3"><div class="card h-100"><img class="product-image card-img-top" [src]="product.image" [alt]="product.title"><div class="card-body d-flex flex-column"><small class="text-primary">{{product.category}}</small><h5 class="mt-2">{{product.title}}</h5><strong class="fs-5">{{product.price | currency:'USD'}}</strong><div class="mt-auto pt-3 d-grid gap-2"><button class="btn btn-primary" (click)="store.addToCart(product)"><i class="bi bi-cart-plus"></i> أضف للسلة</button><button class="btn btn-outline-danger" (click)="store.toggleFavorite(product)"><i class="bi bi-heart-fill"></i> إزالة</button></div></div></div></div>}</div>} @else {<div class="card p-5 text-center"><i class="bi bi-heart fs-1 text-muted"></i><h3 class="mt-3">لا توجد منتجات في المفضلة</h3><a class="btn btn-primary mx-auto" routerLink="/products">ابدأ التسوق</a></div>}</section>` })
export class FavoritesComponent { readonly store = inject(StoreService); }

@Component({ standalone: true, imports: [CommonModule, RouterLink, CurrencyPipe], template: `
<section class="container py-5"><h1 class="fw-bold mb-4">سلة المشتريات</h1>@if (store.cart().length) {<div class="row g-4"><div class="col-lg-8"><div class="card p-3">@for (item of store.cart(); track item.product.id) {<div class="row align-items-center py-3 border-bottom"><div class="col-3 col-md-2"><img class="img-fluid" [src]="item.product.image" [alt]="item.product.title"></div><div class="col-9 col-md-4"><h5>{{item.product.title}}</h5><span class="text-muted">{{item.product.price | currency:'USD'}}</span></div><div class="col-7 col-md-4 mt-3 mt-md-0"><div class="input-group"><button class="btn btn-outline-secondary" (click)="store.changeQuantity(item.product.id,item.quantity-1)">-</button><span class="form-control text-center">{{item.quantity}}</span><button class="btn btn-outline-secondary" (click)="store.changeQuantity(item.product.id,item.quantity+1)">+</button></div></div><div class="col-5 col-md-2 text-end mt-3 mt-md-0"><button class="btn btn-outline-danger" (click)="store.remove(item.product.id)"><i class="bi bi-trash"></i></button></div></div>}</div></div><div class="col-lg-4"><div class="card p-4"><h4>ملخص الطلب</h4><hr><div class="d-flex justify-content-between"><span>الإجمالي</span><strong>{{store.total() | currency:'USD'}}</strong></div><button class="btn btn-success w-100 mt-4" (click)="checkout()">إتمام الطلب</button></div></div></div>} @else {<div class="text-center py-5 card"><i class="bi bi-cart-x fs-1 text-muted"></i><h3>السلة فارغة</h3><a routerLink="/products" class="btn btn-primary mx-auto">ابدأ التسوق</a></div>}</section>` })
export class CartComponent { readonly store = inject(StoreService); checkout() { alert('تم استلام طلبك بنجاح! هذه نسخة Frontend تجريبية.'); } }

@Component({ standalone: true, imports: [FormsModule, RouterLink], template: `
<section class="container py-5"><div class="card mx-auto p-4" style="max-width:500px"><h1 class="h3 fw-bold">تسجيل الدخول</h1><p class="text-muted">ادخل إلى حسابك لإدارة السلة والمفضلة.</p><form (ngSubmit)="login()"><label class="form-label">البريد الإلكتروني</label><input class="form-control mb-3" required type="email" [(ngModel)]="email" name="email" placeholder="name@example.com"><label class="form-label">كلمة المرور</label><input class="form-control mb-3" required type="password" [(ngModel)]="password" name="password" placeholder="••••••••"><button class="btn btn-primary w-100" [disabled]="store.loading()">{{store.loading() ? 'جارٍ الدخول...' : 'دخول'}}</button></form>@if(message){<div class="alert mt-3 mb-0" [class.alert-success]="success" [class.alert-danger]="!success">{{message}}</div>}<p class="text-center text-muted mt-3 mb-0">ليس لديك حساب؟ <a routerLink="/register">إنشاء حساب</a></p></div></section>` })
export class LoginComponent { readonly store = inject(StoreService); private router = inject(Router); email = ''; password = ''; message = ''; success = false; login() { this.store.login(this.email, this.password, (error) => { this.success = !error; this.message = error || 'تم تسجيل الدخول بنجاح.'; if (!error) void this.router.navigateByUrl(this.store.isAdmin() ? '/admin' : '/products'); }); } }

@Component({ standalone: true, imports: [FormsModule, RouterLink], template: `
<section class="container py-5"><div class="card mx-auto p-4" style="max-width:500px"><h1 class="h3 fw-bold">إنشاء حساب</h1><p class="text-muted">أنشئ حسابك لحفظ السلة والمفضلة.</p><form (ngSubmit)="register()"><label class="form-label">الاسم</label><input class="form-control mb-3" required [(ngModel)]="name" name="name"><label class="form-label">البريد الإلكتروني</label><input class="form-control mb-3" required type="email" [(ngModel)]="email" name="email"><label class="form-label">كلمة المرور</label><input class="form-control mb-3" required minlength="8" type="password" [(ngModel)]="password" name="password"><button class="btn btn-primary w-100" [disabled]="store.loading()">{{store.loading() ? 'جارٍ إنشاء الحساب...' : 'إنشاء الحساب'}}</button></form>@if(message){<div class="alert mt-3 mb-0" [class.alert-success]="success" [class.alert-danger]="!success">{{message}}</div>}<p class="text-center text-muted mt-3 mb-0">لديك حساب؟ <a routerLink="/login">تسجيل الدخول</a></p></div></section>` })
export class RegisterComponent { readonly store = inject(StoreService); private router = inject(Router); name = ''; email = ''; password = ''; message = ''; success = false; register() { this.store.register(this.name, this.email, this.password, (error) => { this.success = !error; this.message = error || 'تم إنشاء الحساب بنجاح.'; if (!error) void this.router.navigateByUrl('/products'); }); } }

@Component({ standalone: true, imports: [RouterLink, CurrencyPipe], template: `
<section class="container py-5"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="fw-bold">لوحة التحكم</h1><p class="text-muted">إدارة بيانات المتجر</p></div><a routerLink="/admin/products/new" class="btn btn-success"><i class="bi bi-plus-lg"></i> إضافة منتج</a></div><div class="row g-3 mb-4"><div class="col-md-4"><div class="card p-3"><small>عدد المنتجات</small><strong class="display-6">{{store.products().length}}</strong></div></div><div class="col-md-4"><div class="card p-3"><small>منتجات في السلة</small><strong class="display-6">{{store.cart().length}}</strong></div></div><div class="col-md-4"><div class="card p-3"><small>قيمة السلة</small><strong class="display-6">{{store.total() | currency:'USD'}}</strong></div></div></div><div class="card p-3"><h4>المنتجات الحالية</h4><div class="table-responsive"><table class="table align-middle"><thead><tr><th>المنتج</th><th>التصنيف</th><th>السعر</th></tr></thead><tbody>@for (product of store.products(); track product.id) {<tr><td>{{product.title}}</td><td>{{product.category}}</td><td>{{product.price | currency:'USD'}}</td></tr>}</tbody></table></div></div></section>` })
export class AdminComponent { readonly store = inject(StoreService); }

@Component({ standalone: true, imports: [FormsModule], template: `
<section class="container py-5"><div class="card mx-auto p-4" style="max-width:700px"><h1 class="h3">إضافة منتج جديد</h1><form (ngSubmit)="save()"><div class="row g-3"><div class="col-md-6"><label class="form-label">اسم المنتج</label><input class="form-control" required [(ngModel)]="title" name="title"></div><div class="col-md-6"><label class="form-label">السعر</label><input type="number" class="form-control" required [(ngModel)]="price" name="price"></div><div class="col-md-6"><label class="form-label">التصنيف</label><input class="form-control" required [(ngModel)]="category" name="category"></div><div class="col-md-6"><label class="form-label">رابط الصورة</label><input class="form-control" [(ngModel)]="image" name="image"></div><div class="col-12"><label class="form-label">الوصف</label><textarea class="form-control" [(ngModel)]="description" name="description"></textarea></div></div><button class="btn btn-success mt-4">حفظ المنتج</button></form></div></section>` })
export class ProductFormComponent { private router = inject(Router); private store = inject(StoreService); title=''; price=0; category=''; image='https://via.placeholder.com/300'; description=''; save(): void { this.store.addProduct({title:this.title,price:this.price,category:this.category,image:this.image,description:this.description}, (error) => { if (error) return; void this.router.navigateByUrl('/admin'); }); } }

@Component({ standalone: true, imports: [RouterLink], template: `<section class="container text-center py-5"><h1 class="display-1 fw-bold text-primary">404</h1><h2>الصفحة غير موجودة</h2><p class="text-muted">الرابط الذي طلبته غير متاح.</p><a routerLink="/" class="btn btn-primary">العودة للرئيسية</a></section>` })
export class NotFoundComponent {}
